//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SastoMarket
{


    public partial class signup
    {

        /// <summary>
        /// Button2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        

        protected global::System.Web.UI.WebControls.TextBox Fullname;
        protected global::System.Web.UI.WebControls.TextBox Username;
        protected global::System.Web.UI.WebControls.TextBox Password;
        protected global::System.Web.UI.WebControls.TextBox Dob;
        protected global::System.Web.UI.WebControls.TextBox Address;
        protected global::System.Web.UI.WebControls.TextBox Phone;
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Button2;
    }
}
