//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SastoMarket.User_Profile
{
    public partial class user_women
    {
        protected global::System.Web.UI.WebControls.Repeater Product_Women;
    }
}
